# Generated by Django 4.2 on 2023-04-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="produto", name="adicionais",),
        migrations.RemoveField(model_name="produto", name="categoria",),
        migrations.DeleteModel(name="Adicional",),
        migrations.DeleteModel(name="Categoria",),
        migrations.DeleteModel(name="Opcoes",),
        migrations.DeleteModel(name="Produto",),
    ]
