# Generated by Django 4.1.4 on 2023-04-30 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0002_remove_produto_adicionais_remove_produto_categoria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("maximo", models.IntegerField()),
                ("minimo", models.IntegerField()),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Opcoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=40)),
                ("acrescimo", models.FloatField(default=0)),
                ("ativo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_produto", models.CharField(max_length=500)),
                ("img", models.ImageField(upload_to="post_img")),
                ("preco", models.FloatField()),
                ("descricao", models.TextField()),
                ("ingredientes", models.CharField(max_length=2000)),
                ("ativo", models.BooleanField(default=True)),
                ("adicionais", models.ManyToManyField(blank=True, to="home.adicional")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.categoria"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adicional",
            name="opcoes",
            field=models.ManyToManyField(to="home.opcoes"),
        ),
    ]
