# Generated by Django 4.1.4 on 2023-05-07 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0002_cupomdesconto_alter_pedido_data_pedido_cupom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cupom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pedido.cupomdesconto",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 7, 12, 9, 46, 465271)
            ),
        ),
    ]
